### PR TITLE
support time.Duration for time flags

### PR DESCRIPTION
**Pull request by timkuijsten**
```sh
$ ./filter-spfgreylist -h
Usage of ./filter-spfgreylist:
  -greyexp duration
        duration before greylist attempts expire (default 4h0m0s)
  -passtime duration
        duration before retries are accounted (default 5m0s)
  -whiteexp duration
        duration before whitelists expire (default 720h0m0s)
  -wl-domain string
        filename containing a list of sender domains to whitelist, one per line
  -wl-ip string
        filename containing a list of IP addresses to whitelist, one per line
```

### CODE REVIEW

**Comment by timkuijsten** [comment]
It should be noted that it does break backwards compatibility because an "s" suffix is required if seconds are specified.

**Comment by poolpOrg** [comment]
I really like that 👍🏻

**Comment by poolpOrg** [comment]
thanks !

**Comment by timkuijsten** [comment]
thank you! :)

**Pull request merged**
